# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Fri, 20 Feb 2015 17:29:51 +0000
*               @ALL          1
*               @user         8
